/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type GraphEvent =
  | GraphStartedEvent
  | NodeStartedEvent
  | NodeCompletedEvent
  | RetryLoopEvent
  | GraphInterruptedEvent
  | GraphCompletedEvent
  | GraphErrorEvent;
export type Type = "graph_started";
export type ThreadId = string;
export type EmittedAt = number;
export type Query = string;
export type Type1 = "node_started";
export type ThreadId1 = string;
export type EmittedAt1 = number;
/**
 * Matches the node names registered in api.graph.build.build_graph exactly —
 * these are LangGraph's own node names, not a separate naming scheme.
 */
export type NodeName = "planner" | "retriever" | "reranker" | "generator" | "critic" | "hitl_gate";
export type RunId = string;
export type Type2 = "node_completed";
export type ThreadId2 = string;
export type EmittedAt2 = number;
export type RunId1 = string;
export type LatencyMs = number;
export type Provider = string;
export type Model = string;
export type PromptTokens = number;
export type CompletionTokens = number;
export type TotalTokens = number;
export type EstimatedCostUsd = number;
export type LatencyMs1 = number;
export type LlmCalls = TokenUsage[];
export type Type3 = "retry_loop";
export type ThreadId3 = string;
export type EmittedAt3 = number;
export type FromNode = "critic";
export type ToNode = "retriever";
export type RetryCount = number;
export type Reason = string | null;
export type Type4 = "graph_interrupted";
export type ThreadId4 = string;
export type EmittedAt4 = number;
export type Type5 = "graph_completed";
export type ThreadId5 = string;
export type EmittedAt5 = number;
export type Answer = string | null;
export type Citations = string[];
export type Confidence = number | null;
export type Abstained = boolean;
export type HumanApproved = boolean | null;
export type Type6 = "error";
export type ThreadId6 = string;
export type EmittedAt6 = number;
export type Message = string;
export type Retryable = boolean;
export type Reason1 = ("rate_limited" | "budget_exhausted" | "provider_exhausted" | "input_too_long") | null;

export interface GraphStartedEvent {
  type: Type;
  thread_id: ThreadId;
  emitted_at: EmittedAt;
  query: Query;
  [k: string]: unknown;
}
export interface NodeStartedEvent {
  type: Type1;
  thread_id: ThreadId1;
  emitted_at: EmittedAt1;
  node: NodeName;
  run_id: RunId;
  [k: string]: unknown;
}
export interface NodeCompletedEvent {
  type: Type2;
  thread_id: ThreadId2;
  emitted_at: EmittedAt2;
  node: NodeName;
  run_id: RunId1;
  latency_ms: LatencyMs;
  llm_calls?: LlmCalls;
  payload?: Payload;
  [k: string]: unknown;
}
/**
 * One gateway call's telemetry, captured by api.graph.streaming.RecordingGateway.
 * A node emits zero of these (retriever/reranker/hitl_gate never call the gateway),
 * one (the common case), or two (llm.complete_json's one repair retry).
 */
export interface TokenUsage {
  provider: Provider;
  model: Model;
  prompt_tokens: PromptTokens;
  completion_tokens: CompletionTokens;
  total_tokens: TotalTokens;
  estimated_cost_usd: EstimatedCostUsd;
  latency_ms: LatencyMs1;
  [k: string]: unknown;
}
export interface Payload {
  [k: string]: unknown;
}
/**
 * Fired when the critic decides to loop back to the retriever — the backward edge
 * the frontend needs to animate distinctly from the normal forward flow. Derived from
 * the critic node's own result dict (needs_retry=True), not a separate LangGraph
 * signal — see api.graph.nodes.make_critic_node.
 */
export interface RetryLoopEvent {
  type: Type3;
  thread_id: ThreadId3;
  emitted_at: EmittedAt3;
  from_node?: FromNode;
  to_node?: ToNode;
  retry_count: RetryCount;
  reason?: Reason;
  [k: string]: unknown;
}
/**
 * The graph paused inside hitl_gate's interrupt() call. `interrupt` is the raw
 * payload passed to interrupt() in api.graph.nodes.make_hitl_gate_node — either the
 * out_of_scope framing or the review (draft answer) framing.
 */
export interface GraphInterruptedEvent {
  type: Type4;
  thread_id: ThreadId4;
  emitted_at: EmittedAt4;
  interrupt: Interrupt;
  [k: string]: unknown;
}
export interface Interrupt {
  [k: string]: unknown;
}
/**
 * The graph reached END without pausing — hitl_gate auto-approved because
 * confidence was already high enough (see api.graph.nodes._needs_human_review).
 */
export interface GraphCompletedEvent {
  type: Type5;
  thread_id: ThreadId5;
  emitted_at: EmittedAt5;
  answer: Answer;
  citations: Citations;
  confidence: Confidence;
  abstained: Abstained;
  human_approved: HumanApproved;
  [k: string]: unknown;
}
/**
 * A gateway failure (AllProvidersExhausted/BudgetExceeded) propagated out of a
 * node mid-stream, or a pre-graph rejection (rate limit) emitted before any node
 * runs. SSE can't change the HTTP status after headers are sent, so this is the
 * in-band equivalent of the non-streaming path's 503/429.
 *
 * `reason` is a structured discriminator for the frontend to branch on directly
 * instead of pattern-matching `message` text — `None` for the original
 * AllProvidersExhausted/per-request-budget cases (unchanged since before this field
 * existed), set for the demo-hardening cases added alongside it.
 */
export interface GraphErrorEvent {
  type: Type6;
  thread_id: ThreadId6;
  emitted_at: EmittedAt6;
  message: Message;
  retryable: Retryable;
  reason?: Reason1;
  [k: string]: unknown;
}
